In [1]:
import os
import string
import csv
import re
import numpy as np
import pandas as pd
from osgeo import gdal

from time import time
from math import floor
from pandas import Timestamp
from dateutil.parser import parse#从字符串转为日期的格式

ModuleNotFoundError: No module named 'osgeo'

In [2]:
orders = ['Pelecaniformes', 'Gruiformes', 'Passeriformes', 'Suliformes', 'Ciconiiformes',
 'Falconiformes', 'Charadriiformes', 'Anseriformes', 'Accipitriformes', 'Procellariiformes']

In [78]:
def y3(x):
    y = []
    for i in range(1,13):
        y.append(x+str(i))
    return y

add_columns = list(np.array(list(map(y3, orders))).reshape([1,-1])[0])

In [7]:
csvFile = open("./2.3.2.1Location.csv",'w',newline='',encoding='utf-8')
writer = csv.writer(csvFile)
csvRow = []

f = open("2.3.2.1Location.txt",'r',encoding='GB2312')
for line in f:
    csvRow = line.split()
    writer.writerow(csvRow)

f.close()
csvFile.close()

In [21]:
random_df = pd.read_csv(r'2.3.2.1Location.csv')
random_df['lon']=random_df['long']
random_df.drop(['long'],inplace=True,axis=1)

In [22]:
tif_path = r'D:\world virus&bird\map_raster/'
i = 'Accipitriformes1.tif'
env_data = gdal.Open(tif_path+i)#tiff数据
inf = env_data.GetGeoTransform()#tif坐标信息数据
raster_X = env_data.RasterXSize
raster_Y = env_data.RasterYSize
del env_data

In [23]:
## get index
t1 = time()
   
random_df['lat']=pd.to_numeric(random_df['lat'])
random_df['lon']=pd.to_numeric(random_df['lon'])
          
random_df['lon_indx'] = random_df.lon.apply(lambda x:round((x-inf[0])/inf[1]))
random_df['lat_indx'] = random_df.lat.apply(lambda x:round((x-inf[3])/inf[5]))
             
random_df['lon_indx'] = random_df.lon_indx.apply(lambda x: raster_X-1  if x>=raster_X else x)
random_df['lat_indx'] = random_df.lat_indx.apply(lambda x: raster_Y-1  if x>=raster_Y else x)

print(time()-t1)

0.005004405975341797

In [28]:
raster_df = random_df.copy()

In [47]:
'''
def sortkey(s):
    return re.findall(r"[-+]?\d*\.\d+|\d+",s)'''

'\ndef sortkey(s):\n    return re.findall(r"[-+]?\\d*\\.\\d+|\\d+",s)'

In [84]:
for file in add_columns:
    filename = os.path.splitext(file)[0]
    env_data = gdal.Open(os.path.join(tif_path,'%s.tif'%file))#tiff数据
    band = env_data.GetRasterBand(1).ReadAsArray()
    raster_df = raster_df.copy()
    raster_df[filename] = raster_df.apply(lambda x:band[x['lat_indx']][x['lon_indx']],axis=1)

In [86]:
raster_df

,Location,lat,lon,lon_indx,lat_indx,Accipitriformes1,Accipitriformes10,Accipitriformes11,Accipitriformes12,Accipitriformes2,...,Suliformes11,Suliformes12,Suliformes2,Suliformes3,Suliformes4,Suliformes5,Suliformes6,Suliformes7,Suliformes8,Suliformes9
0,Africa,8.026693,-7.546616,690,328,0.561830,0.241159,0.542807,0.554089,0.552492,...,0.308870,0.308870,0.308870,0.308870,0.308870,0.308870,0.308870,0.308870,0.308870,0.308870
1,CA,25.520260,83.473704,1054,258,0.484793,0.520094,0.480450,0.474815,0.521499,...,0.308861,0.308861,0.308861,0.315604,0.309632,0.309632,0.309700,0.309700,0.309700,0.309815
2,Europe,49.512838,11.784004,767,162,0.163450,0.209330,0.200967,0.163534,0.173765,...,0.308796,0.308818,0.308796,0.308796,0.308796,0.308796,0.308796,0.308796,0.308796,0.308796
3,JapanKorea,38.389548,140.234209,1281,206,0.750834,0.630911,0.772303,0.767519,0.758603,...,0.308841,0.308787,0.308787,0.318366,0.308841,0.308796,0.308796,0.308796,0.316271,0.308796
4,Mongolia,47.953116,102.837314,1131,168,0.059337,0.248137,0.067377,0.048919,0.081558,...,0.308847,0.308847,0.308847,0.308824,0.308847,0.308802,0.308802,0.308802,0.308802,0.308802
5,NChina,38.273597,111.853957,1167,207,0.056532,0.388158,0.256034,0.079659,0.142808,...,0.308841,0.308789,0.308841,0.308841,0.308841,0.308796,0.308796,0.308796,0.308796,0.308796
6,Qinghai,36.985947,100.028852,1120,212,0.038013,0.213862,0.173833,0.048281,0.042856,...,0.331727,0.331767,0.311132,0.311132,0.311132,0.311132,0.311132,0.363694,0.356969,0.311162
7,Russia,57.004160,101.654804,1127,132,0.031309,0.070784,0.031427,0.031310,0.031583,...,0.308841,0.308818,0.308818,0.308841,0.308841,0.308841,0.308796,0.308796,0.308796,0.308796
8,SChina,24.044104,112.149584,1169,264,0.330633,0.290021,0.202727,0.171480,0.362025,...,0.308796,0.308796,0.308796,0.308796,0.308796,0.316271,0.316271,0.316271,0.316271,0.316271
9,SEA,13.743950,102.366493,1129,305,0.737592,0.631629,0.768112,0.776433,0.663520,...,0.313714,0.320635,0.309731,0.311711,0.313524,0.311644,0.311615,0.311615,0.309806,0.311644
10,WA,34.100010,43.268346,893,224,0.111487,0.268746,0.139440,0.117409,0.136636,...,0.374092,0.316402,0.308865,0.308828,0.308761,0.308749,0.322819,0.322819,0.322819,0.320018

In [87]:
raster_df.to_csv(r'2.3.2.1_bird.csv',index=False)

### 测试代码

In [24]:
raster_df.shape

(68000, 34)

In [25]:
temp_df

,point,HPD85,HPD25,HPD20,HPD75,HPD90,HPD15,HPD10,HPD80,HPD65,...,Pelecaniformes,Gruiformes,Passeriformes,Suliformes,Ciconiiformes,Falconiformes,Charadriiformes,Anseriformes,Accipitriformes,Procellariiformes
startTime,,,,,,,,,,,,,,,,,,,,,
2006/12/15,"{'type': 'Point', 'coordinates': [60.984816140...",0,0,0,0,0,0,0,0,0,...,0.029947,0.044772,0.048281,0.308842,0.036509,0.031125,0.034633,0.037530,0.034983,0.191765
2006/12/15,"{'type': 'Point', 'coordinates': [-120.8826361...",0,0,0,0,0,0,0,0,0,...,0.034538,0.072467,0.040109,0.308796,0.033895,0.027615,0.027212,0.029567,0.040376,0.161562
2006/12/15,"{'type': 'Point', 'coordinates': [-87.68970348...",0,0,0,0,0,0,0,0,0,...,0.025759,0.025266,0.034662,0.308796,0.032435,0.025101,0.030935,0.039595,0.030405,0.161569
2006/12/15,"{'type': 'Point', 'coordinates': [-76.54175732...",0,0,0,0,0,0,0,0,0,...,0.029981,0.041906,0.033960,0.308992,0.031949,0.055339,0.034038,0.080767,0.033574,0.161569
2006/12/15,"{'type': 'Point', 'coordinates': [-44.88966479...",0,0,0,0,0,0,0,0,0,...,0.026149,0.024458,0.033907,0.309000,0.025079,0.024939,0.025665,0.026971,0.024718,0.174206
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017/12/15,"{'type': 'Point', 'coordinates': [-24.37018632...",0,0,0,0,0,0,0,0,0,...,0.025956,0.025326,0.103897,0.308796,0.033286,0.025144,0.032613,0.093150,0.030527,0.166967
2017/12/15,"{'type': 'Point', 'coordinates': [130.48579292...",0,0,0,0,0,0,0,0,0,...,0.025332,0.024296,0.187601,0.311094,0.322905,0.026818,0.047984,0.039771,0.081569,0.161594
2017/12/15,"{'type': 'Point', 'coordinates': [-64.75744202...",0,0,0,0,0,0,0,0,0,...,0.031879,0.037547,0.623351,0.308796,0.126757,0.032054,0.064398,0.053543,0.683670,0.161562
2017/12/15,"{'type': 'Point', 'coordinates': [121.70289112...",0,0,0,0,0,0,0,0,0,...,0.024945,0.048424,0.038318,0.308796,0.028478,0.025240,0.030407,0.028201,0.031918,0.161562
2017/12/15,"{'type': 'Point', 'coordinates': [-68.54090982...",0,0,0,0,0,0,0,0,0,...,0.024820,0.026984,0.038036,0.308789,0.037841,0.025103,0.028693,0.045813,0.035210,0.161603

In [26]:
raster_df.to_csv(r'/home/wb/Documents/virus_analysis/virus_dispersal/2.3.2.1_HPD_files/dataset_2.3.2.1_.csv')

In [35]:
raster_df1 = raster_df.infer_objects()
cor_matrix = raster_df1.corr()

In [42]:
cor_matrix['HPD50']

HPD85                0.509438
HPD25                0.542898
HPD20                0.468622
HPD75                0.642626
HPD90                0.454171
HPD15                0.413201
HPD10                0.312254
HPD80                0.573137
HPD65                0.771177
HPD35                0.714267
HPD50                1.000000
HPD95                0.387902
HPD60                0.830146
HPD40                0.802300
HPD55                0.914805
HPD70                0.705056
HPD30                0.628075
HPD45                0.896627
lon                  0.078010
lat                 -0.027792
month               -0.009525
lon_indx             0.078016
lat_indx             0.027781
Pelecaniformes       0.045795
Gruiformes          -0.016471
Passeriformes        0.054485
Suliformes           0.011422
Ciconiiformes        0.048478
Falconiformes        0.001613
Charadriiformes      0.014343
Anseriformes        -0.014878
Accipitriformes      0.068721
Procellariiformes   -0.000885
Name: HPD50, dtype: float64

In [19]:
#tif_path = r'/home/wb/Documents/landcover/'
#p_path = r'/home/wb/Documents/world bird/monthly_bird/binaryset_nc/'
#out_path = r'/home/wb/Documents/world bird/monthly_bird/completed_dataset/'
t1 = time()
os.chdir(p_path)
for i in os.listdir():
    filetype = os.path.splitext(i)[1]
    filename = os.path.splitext(i)[0]
    print(filename)
    if filetype == '.csv':
        gps_point = pd.read_csv(i,engine = 'c')
        gps_point = gps_point#[:20]
   
        gps_point['lat']=pd.to_numeric(gps_point['lat'])
        gps_point['lon']=pd.to_numeric(gps_point['lon'])
          
        gps_point['lon_indx'] = gps_point.lon.apply(lambda x:round((x-inf[0])/inf[1]))
        gps_point['lat_indx'] = gps_point.lat.apply(lambda x:round((x-inf[3])/inf[5]))
             
        gps_point['lon_indx'] = gps_point.lon_indx.apply(lambda x: raster_X-1  if x>=raster_X else x)
        gps_point['lat_indx'] = gps_point.lat_indx.apply(lambda x: raster_Y-1  if x>=raster_Y else x)
        for tif in os.listdir(tif_path):
            tiftype = os.path.splitext(tif)[1]
            tifname = os.path.splitext(tif)[0]
            if tiftype == '.tif':
                env_data = gdal.Open(tif_path+tif)#tiff数据
                band = env_data.GetRasterBand(1).ReadAsArray()
                gps_point[tifname] = gps_point.apply(lambda x:int(band[x['lat_indx']][x['lon_indx']]),axis=1)   
                
        gps_point = gps_point.drop(['lon_indx','lat_indx'],axis=1)
        gps_point.to_csv(out_path+filename+".csv",index = False,encoding="utf_8_sig")

,point,HPD90,HPD30,HPD95,HPD75,HPD65,HPD25,HPD10,HPD85,HPD35,...,HPD70,HPD80,HPD50,HPD60,HPD15,HPD40,HPD55,HPD45,lon,lat
startTime,,,,,,,,,,,,,,,,,,,,,
2008/02/15,"{'type': 'Point', 'coordinates': [152.96980282...",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,152.969803,67.157369
2008/02/15,"{'type': 'Point', 'coordinates': [-62.46339380...",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,-62.463394,53.293420
2008/02/15,"{'type': 'Point', 'coordinates': [80.057363520...",1,0,1,1,0,0,0,1,0,...,0,1,0,0,0,0,0,0,80.057364,34.769852
2008/02/15,"{'type': 'Point', 'coordinates': [-87.38230985...",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,-87.382310,39.685640
2008/02/15,"{'type': 'Point', 'coordinates': [115.39810433...",1,0,1,1,0,0,0,1,0,...,0,1,0,0,0,0,0,0,115.398104,46.746211
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017/12/15,"{'type': 'Point', 'coordinates': [-80.11101417...",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,-80.111014,76.485276
2017/12/15,"{'type': 'Point', 'coordinates': [-6.170567922...",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,-6.170568,26.018110
2017/12/15,"{'type': 'Point', 'coordinates': [-15.38760146...",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,-15.387601,65.260628
2017/12/15,"{'type': 'Point', 'coordinates': [-115.7513269...",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,-115.751327,50.129252
2017/12/15,"{'type': 'Point', 'coordinates': [90.797498893...",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,90.797499,29.792692

In [28]:
c = random_df.point.iloc[0]
c = eval(c)

In [29]:
c['coordinates']

[152.969802821, 67.1573692697]

AttributeError: 'str' object has no attribute 'coordinates'